

tellraw_colors = {
	"dark_red":11141120,
	"red":16733525,
	"gold":16755200	,
	"yellow":16777045,
	"dark_green":43520,
	"green":5635925,
	"aqua":5636095,
	"dark_aqua":43690,
	"dark_blue":170,
	"blue":5592575,
	"light_purple":16733695,
	"dark_purple":11141290,
	"white":0,
	"gray":5592405,
	"dark_gray":11184810,
	"black":16777215,
}

death_messages = {
	"fell off a ladder":False,
  "fell off some vines":False,
  "fell out of the water":False,
  "fell from a high place":False,
  "was doomed to fall":False,
  "was doomed to fall by":True,
  "was doomed to fall by using":True,
  "fell too far and was finished by":True,
  "fell too far and was finished by using":True,
  "was struck by lightning":False,
  "was struck by lightning whilst fighting":False,
  "went up in flames":False,
  "walked into fire whilst fighting":True,
  "burned to death":False,
  "was burnt to a crisp whilst fighting":True,
  "tried to swim in lava":False,
  "tried to swim in lava to escape":True,
  "discovered the floor was lava":False,
  "walked into danger zone due to":True,
  "suffocated in a wall":False,
  "suffocated in a wall whilst fighting":True,
  "was squished too much":False,
  "was squashed by":True,
  "drowned":False,
  "drowned whilst trying to escape":True,
  "starved to death":False,
  "starved to death whilst fighting":True,
  "was pricked to death":False,
  "walked into a cactus whilst trying to escape":True,
  "died":False,
  "died because of":True,
  "blew up":False,
  "was blown up by":True,
  "was blown up by using":True,
  "was killed by magic":False,
  "was killed by even more magic":False,
  "withered away":False,
  "withered away whilst fighting":True,
  "was squashed by a falling anvil":False,
  "was squashed by a falling anvil whilst fighting":True,
  "was squashed by a falling block":False,
  "was squashed by a falling block whilst fighting":True,
  "was slain by":True,
  "was slain by using":True,
  "was slain by":True,
  "was slain by using":True,
  "was shot by":True,
  "was shot by using":True,
  "was fireballed by":True,
  "was fireballed by using":True,
  "was pummeled by":True,
  "was pummeled by using":True,
  "was killed by using magic":True,
  "was killed by using":True,
  "was killed trying to hurt":True,
  "was killed by trying to hurt":True,
  "was impaled by":True,
  "was impaled by with":True,
  "hit the ground too hard":False,
  "hit the ground too hard whilst trying to escape":True,
  "fell out of the world":False,
  "didn't want to live in the same world as":True,
  "was roasted in dragon breath":False,
  "was roasted in dragon breath by":True,
  "experienced kinetic energy":False,
  "experienced kinetic energy whilst trying to escape":True,
  "went off with a bang":False,
  "went off with a bang whilst fighting":True,
  "was killed by":False,
  "Intentional Game Design":False,
  "was poked to death by a sweet berry bush":False,
  "was poked to death by a sweet berry bush whilst trying to escape":True
}


